version: "3.7"

services:
  master:
    build: .
    command: ./mke server --enable-worker
    # privileged: true
    volumes:
      - ../../mke:/mke
      - ./script.sh:/script.sh
      - master:/var/lib/mke
    ports:
      - "6443:6443"
    networks:
      proxy:
  worker:
    build: .
    command: ./mke worker $TOKEN
    # privileged: true
    volumes:
      - ../../mke:/mke
      - worker:/var/lib/mke
    networks:
      proxy:
networks:
  proxy:
volumes:
  master:
    # - /var/lib/mke
  worker:
